Update Backendeploy.yml

diff --git a/.github/workflows/Backendeploy.yml b/.github/workflows/Backendeploy.yml
--- a/.github/workflows/Backendeploy.yml
+++ b/.github/workflows/Backendeploy.yml
@@ -29,10 +29,10 @@ jobs:
             set -e
             cd "${{ secrets.WORK_DIR }}" || { echo "No se puede acceder a WORK_DIR"; exit 1; }
             if [ ! -d .git ]; then
-              git clone --branch "${{ secrets.MAIN_BRANCH }}" https://github.com/jesusjg3/gestionhotelera.git . || { echo "Error en git clone"; exit 1; }
+              git clone --branch "main" https://github.com/jesusjg3/gestionhotelera.git . || { echo "Error en git clone"; exit 1; }
             else
               git fetch origin || { echo "Error en git fetch"; exit 1; }
-              git reset --hard origin/"${{ secrets.MAIN_BRANCH }}" || { echo "Error en git reset"; exit 1; }
+              git reset --hard origin/"main" || { echo "Error en git reset"; exit 1; }
             fi
             composer install --no-dev --prefer-dist --optimize-autoloader --no-interaction || { echo "Error en composer install"; exit 1; }
             php artisan migrate --force || { echo "Error en artisan migrate"; exit 1; }
